name: Update Table of Contents

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Update Table of Contents
      run: |
        # Find all markdown files in the "topics" directory
        markdown_files=$(find topics -name "*.md")

        # Generate table of contents
        toc=""
        current_dir=""
        for file in $markdown_files; do
          # Extract directory name
          dir=$(dirname "$file")
          
          # If the directory changes, add a new section
          if [ "$dir" != "$current_dir" ]; then
            current_dir="$dir"
            dir_name=$(basename "$dir")
            toc="$toc\n- [$dir_name](./$dir)"
          fi
          
          # Format entry for the table of contents
          entry="  - [$(basename "$file" .md)](./$file)"
          
          # Add entry to the appropriate section based on the directory
          toc="$toc\n$entry"
        done


        # Update the README.md file with the generated table of contents
        echo -e "# Table of Contents\n$toc" > README.md

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
          author_name: OG-Jons
          author_email: jonas@marschall.pro
          message: 'Update Table of Contents'
          add: 'README.md'

