name: Update Table of Contents

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Update Table of Contents
      run: |
        # Function to generate table of contents
        generate_toc() {
          local dir=$1
          local indent=$2
        
          # Find all markdown files in the directory
          local markdown_files=$(find "$dir" -maxdepth 1 -name "*.md")
        
          # Generate table of contents
          local toc=""
          for file in $markdown_files; do
            # Format entry for the table of contents
            local entry="${indent}- [$(basename "$file" .md | sed 's/_/ /g' | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')](./$file)"
            # Add entry to the table of contents
            toc="$toc\n$entry"
          done
        
          # Recursively generate table of contents for subdirectories
          local subdirs=$(find "$dir" -mindepth 1 -maxdepth 1 -type d)
          for subdir in $subdirs; do
            # Add a new section for the subdirectory
            local subdir_name=$(basename "$subdir" | sed 's/_/ /g' | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
            toc="$toc\n${indent}- [$subdir_name](./$subdir)"
            # Generate table of contents for the subdirectory
            toc="$toc\n$(generate_toc "$subdir" "$indent\t")"
          done
        
          printf "$toc"
        }
        
        # Find the marker in the README.md file
        marker="<!--TABLE_OF_CONTENTS_MARKER-->"
        marker_line=$(grep -n "$marker" README.md | cut -d ":" -f 1)
        
        # If the marker is found, update the table of contents
        if [ -n "$marker_line" ]; then
          # Generate table of contents
          toc=$(generate_toc "topics" "")
        
          # Get the content before the marker
          head -n $(($marker_line)) README.md > temp.txt
        
          # Append the new table of contents
          echo "$toc" >> temp.txt
        
          # Replace the old README with the new one
          mv temp.txt README.md
        else
          echo "Marker not found in README.md. Add <!--TABLE_OF_CONTENTS_MARKER--> to indicate where the table of contents should be inserted."
        fi

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Update Table of Contents'
          add: 'README.md'

