name: Update Table of Contents

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Update Table of Contents
      run: |
        # Find the marker in the README.md file
        marker="<!--TABLE_OF_CONTENTS_MARKER-->"
        marker_line=$(grep -n "$marker" README.md | cut -d ":" -f 1)
        
        # If the marker is found, update the table of contents
        if [ -n "$marker_line" ]; then
          echo "Line $marker_line"
          # Find all markdown files in the "topics" directory
          markdown_files=$(find topics -name "*.md")

          # Generate table of contents
          toc=""
          current_dir=""
          for file in $markdown_files; do
            # Extract directory name
            dir=$(dirname "$file")
            
            # If the directory changes, add a new section
            if [ "$dir" != "$current_dir" ]; then
              current_dir="$dir"
              dir_name=$(basename "$dir" | sed 's/_/ /g' | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
              toc="$toc\n- [$dir_name](./$dir)"
            fi
            
            # Format entry for the table of contents
            entry="  - [$(basename "$file" .md | sed 's/_/ /g' | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')](./$file)"
            
            # Add entry to the appropriate section based on the directory
            toc="$toc\n$entry"
          done

          # Update the table of contents in the README.md file
          awk -v toc="$toc" -v marker_line="$marker_line" 'NR == marker_line + 1 {print toc} {print}' README.md > README.md.tmp
          mv README.md.tmp README.md
        else
          echo "Marker not found in README.md. Add <!--TABLE_OF_CONTENTS_MARKER--> to indicate where the table of contents should be inserted."
        fi

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'Update Table of Contents'
          add: 'README.md'

